// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pr07_WebAPI.Data;

#nullable disable

namespace Pr07_WebAPI.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pr07_WebAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            Title = "Clean Code",
                            Year = 2008
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Hunt & David Thomas",
                            Title = "The Pragmatic Programmer",
                            Year = 1999
                        },
                        new
                        {
                            Id = 3,
                            Author = "Erich Gamma et al.",
                            Title = "Design Patterns: Elements of Reusable Object-Oriented Software",
                            Year = 1994
                        },
                        new
                        {
                            Id = 4,
                            Author = "Martin Fowler",
                            Title = "Refactoring: Improving the Design of Existing Code",
                            Year = 1999
                        },
                        new
                        {
                            Id = 5,
                            Author = "Eric Evans",
                            Title = "Domain-Driven Design: Tackling Complexity in the Heart of Software",
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
